#!/bin/bash
set -o errexit

PRODUCT_BUILD_PARAMS=""

while getopts "pdtxj:" opt; do
        case $opt in
		x)
			# debug
			echo "Maven debug mode"
			DEBUG="--debug"
			;;
        	p)
                        # build product
                        PROD=$opt
			echo "Product build"
                        PRODUCT_BUILD_PARAMS="-Dproduct -Dinsecure.repositories=WARN -DskipTestsuite -DskipTests"
                        ;;
		d)
			# just distribution
			DIST=$opt
			echo "Distribution build"
			;;
		t)
			# test arifacts
			TA=$opt
			echo "Test artifacts build"
			;;
                j)
                        # set JAVA_HOME
                        source kc-java-selector ${OPTARG}
                        ;;
		s)
			# skip testsuite build
			TS_SKIP="-DskipTestsuite"
			echo "Skip TestSuite build"
			;;
   		\?)
                        echo "Invalid option: -$OPTARG" >&2
			exit
                        ;;
        esac
done

if [ ${DIST}x == x ] ; then
	mvn $DEBUG clean install -DskipTests $TS_SKIP $PRODUCT_BUILD_PARAMS
	mvn $DEBUG clean install -f distribution/pom.xml $PRODUCT_BUILD_PARAMS
else
	mvn $DEBUG clean install -f distribution/pom.xml $PRODUCT_BUILD_PARAMS
fi
if [ ${TA}x != x ] ; then
	mvn $DEBUG clean install -f testsuite/pom.xml -DskipTests $PRODUCT_BUILD_PARAMS
	mvn $DEBUG clean install -f testsuite/integration-arquillian/servers/pom.xml $PRODUCT_BUILD_PARAMS
	mvn $DEBUG clean install -f testsuite/integration-arquillian/test-apps/pom.xml $PRODUCT_BUILD_PARAMS
fi

