#!/bin/bash
set -o errexit

PRODUCT_BUILD_PARAMS=""

while getopts "pdt" opt; do
        case $opt in
        	p)
                        # build product
                        PROD=$opt
			echo "Product build"
                        PRODUCT_BUILD_PARAMS="-Dproduct -Dinsecure.repositories=WARN"
                        ;;
		d)
			# just distribution
			DIST=$opt
			echo "Distribution build"
			;;
		t)
			# test arifacts
			TA=$opt
			echo "Test artifacts build"
			;;
                \?)
                        echo "Invalid option: -$OPTARG" >&2
			exit
                        ;;
        esac
done


mvn clean install -DskipTests $PRODUCT_BUILD_PARAMS
if [ ${DIST}x == x ] ; then
	mvn clean install -DskipTests $PRODUCT_BUILD_PARAMS
	mvn clean install -f distribution/pom.xml $PRODUCT_BUILD_PARAMS
else
	mvn clean install -f distribution/pom.xml $PRODUCT_BUILD_PARAMS
fi
if [ ${TA}x != x ] ; then
	mvn clean install -f testsuite/integration-arquillian/servers/pom.xml $PRODUCT_BUILD_PARAMS
	mvn clean install -f testsuite/integration-arquillian/test-apps/pom.xml $PRODUCT_BUILD_PARAMS
fi

