#!/bin/bash

# set and export JAVA_HOME variable
if [ ${1} == 'openjdk-8' ] ; then
	export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
elif [ ${1} == 'openjdk-11' ] ; then
    export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
elif [ ${1} == 'openjdk-openj9-11' ] ; then
    export JAVA_HOME=/opt/jvm/openjdk-openj9-11
elif [ ${1} == 'jdk-8' ] ; then
    export JAVA_HOME=/opt/jvm/jdk-8
elif [ ${1} == 'jdk-11' ] ; then
    export JAVA_HOME=/opt/jvm/jdk-11
elif [ ${1} == 'ibm-8' ] ; then
    export JAVA_HOME=/opt/jvm/ibm-8
else
    echo "JAVA_HOME not specified or recognized: -$OPTARG" >&2
fi

